### PR TITLE
Packing the code

### PR DESCRIPTION
**Pull request by druvus**
This PR adds a setup script for easier installation of the code by making a recycler package. The documentation is updated to fit the changes. 

I think packing it in this way will simplify usage of your program and it will also open possibilites to install using pypi or bioconda.

### CODE REVIEW

**Comment by shenwei356** [comment]
Great PR! But they seems not active in Github.

**Comment by rozovr** [comment]
Agreed, and apologies for my delay. Thanks again @druvus

**Comment by druvus** [comment]
@rozovr thanks for merging it! 

It seems that something got wrong with the newest release. I can't see setup.py within the rekeased tagged  compressed source code. Downloading the source code based on the latest commit worked fine.

**Comment by druvus** [comment]
@shenwei356 @rozovr I have added recycler to the bioconda project if you would like an easy way to install it.

**Comment by rozovr** [comment]
Thanks for the heads up & bioconda add. 
Re: tagged release - I'll correct & update.

**Comment by rozovr** [comment]
@druvus,  I introduced a new release to address the issue

**Pull request merged**
